apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-push
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: gitcommitmessage
    value: $(body.head_commit.message)